# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiInfo < Formula
  desc "Get CI related information"
  homepage "https://github.com/suzuki-shunsuke/ci-info"
  version "2.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.3.1/ci-info_2.3.1_darwin_amd64.tar.gz"
      sha256 "12ccac8418415e5f28012e864e1714a84636c3720f2166b9a3b27e15393870c6"

      def install
        bin.install "ci-info"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.3.1/ci-info_2.3.1_darwin_arm64.tar.gz"
      sha256 "7fec0b88d213986b16605dd8e64f6230e4b4fc605a0ce4c2fd9698fdc40d3e2d"

      def install
        bin.install "ci-info"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.3.1/ci-info_2.3.1_linux_amd64.tar.gz"
        sha256 "66c78bebe4c4b0ce28e7aa5cd06fdab9db12e9d4116be9135224dee55b94cf38"

        def install
          bin.install "ci-info"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.3.1/ci-info_2.3.1_linux_arm64.tar.gz"
        sha256 "5758eac473d6bff381761b2aa88218ee28828666e799c10e856417a89e77928c"

        def install
          bin.install "ci-info"
        end
      end
    end
  end

  test do
    system "#{bin}/ci-info --version"
  end
end
