# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiInfo < Formula
  desc "Get CI related information"
  homepage "https://github.com/suzuki-shunsuke/ci-info"
  version "2.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.2.0/ci-info_2.2.0_darwin_amd64.tar.gz"
      sha256 "4674bde0a7a701e50ddbf0dfae8097f42785115f28ed6f265c42b2f08ea2891f"

      def install
        bin.install "ci-info"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.2.0/ci-info_2.2.0_darwin_arm64.tar.gz"
      sha256 "55e7cc74f1190f2fbd598ed9f5db874780bc72d06b5db1015ad62e7e9b493eec"

      def install
        bin.install "ci-info"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.2.0/ci-info_2.2.0_linux_amd64.tar.gz"
        sha256 "ffe1f6d0a94ac9c720fa53efa3cdb7d5dbc4bace4e011376babde0d21db8f089"

        def install
          bin.install "ci-info"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v2.2.0/ci-info_2.2.0_linux_arm64.tar.gz"
        sha256 "29767a2f8c06c4d1e777877bde6ed1d322b9a065a0b9995851b33c8108dd581e"

        def install
          bin.install "ci-info"
        end
      end
    end
  end

  test do
    system "#{bin}/ci-info --version"
  end
end
