# This file was generated by GoReleaser. DO NOT EDIT.
cask "ci-info" do
  name "ci-info"
  desc "Get CI related information"
  homepage "https://github.com/suzuki-shunsuke/ci-info"
  version "2.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ci-info"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_amd64.tar.gz"
      sha256 "c692b725e6ff6400edb0db26c82510020144f15fd264531b538d29a777596e9f"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_arm64.tar.gz"
      sha256 "4d0c55f836f5d851982483ccc02b2c08c659b672344fcd945ef6ed0553b3052f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_amd64.tar.gz"
      sha256 "93b73dc07bcff1f05a067582a82437cd7f44b835e8056ce7dc2c83b9855544a7"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_arm64.tar.gz"
      sha256 "fa8ce260b8943e5e80d7f52a92a4736b609159a00f29c00eb6162ef6f1416cdb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-info"]
    end
  end

  # No zap stanza required
end
