# This file was generated by GoReleaser. DO NOT EDIT.
cask "ci-info" do
  name "ci-info"
  desc "Get CI related information"
  homepage "https://github.com/suzuki-shunsuke/ci-info"
  version "2.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ci-info"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_amd64.tar.gz"
      sha256 "1862d5a77b4fe2b4a9d7622699a0027278b542d43538cf4ec3d955b1e6d6a8c0"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_arm64.tar.gz"
      sha256 "3a7237021550633d6db8db3ba2531cb069c75d2e3556e4e4573fe07f20644832"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_amd64.tar.gz"
      sha256 "059ba5a0ef29e8327f82d209bd08a04a02631e967f86836cbff869602aa93b75"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_arm64.tar.gz"
      sha256 "df6afa9e9789ab10decafa09685404f0fa252a0639842a0cd535e5c644fe2501"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-info"]
    end
  end

  # No zap stanza required
end
