# This file was generated by GoReleaser. DO NOT EDIT.
cask "ci-info" do
  name "ci-info"
  desc "Get CI related information"
  homepage "https://github.com/suzuki-shunsuke/ci-info"
  version "2.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ci-info"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_amd64.tar.gz"
      sha256 "1b12b1fffdae8ba3a9a79d14ce39bdc3c3b9d1429d08a6029cbb6ee3d1fd4c88"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_darwin_arm64.tar.gz"
      sha256 "f4b9a92f03073256cf4f87b69e657d1f2ec8f38c64a255efe543e523d995cf77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_amd64.tar.gz"
      sha256 "b11776bd556c2bd6c22ec44f0f19b5244ed8f119ff7e89a3b63cf4c30ae6b1b3"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ci-info/releases/download/v#{version}/ci-info_#{version}_linux_arm64.tar.gz"
      sha256 "ae0952da8cb2decfb4d2e9aaac1ef676e804625212a1e90765fc34f472fc4745"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-info"]
    end
  end

  # No zap stanza required
end
